/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.2/samples
 */
repositories {
    mavenCentral()
}

val codec = configurations.create("codec") {
    attributes {
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.JAVA_RUNTIME))
    }
    isVisible = false
    isCanBeConsumed = false
    isCanBeResolved = true
}

dependencies {
    codec("commons-codec:commons-codec:1.9")
}

tasks.register<CreateMD5>("md5") {
    codecClasspath.from(codec)
    destinationDirectory.set(project.layout.buildDirectory.dir("md5"))
    source(project.layout.projectDirectory.file("src"))
}